name: 'Translation Check'
description:
  'Check if all keys in the main translation file are present in the other
  translation files'
author: 'Krzysztof Duda'

branding:
  icon: 'heart'
  color: 'blue'

inputs:
  main_translation_path:
    description: 'The path to the main translation file'
    required: true
    default: './src/locales/en.json'
  translation_paths:
    description: 'The paths to the translation files, separated by commas'
    required: true
    default: './src/locales/*.json'

runs:
  using: node20
  main: dist/index.js
